language: node_js

# enable c++11/14 builds
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test','llvm-toolchain-precise-3.8' ]
    packages: [ 'libstdc++-4.9-dev','clang-3.8' ]

install:
  - npm install --verbose

script:
  - npm test

matrix:
  include:
    - os: linux
      node_js: 4
      sudo: false
      env: CXX='clang++-3.8'
    - os: linux
      node_js: 6
      sudo: false
      env: CXX='clang++-3.8'
    - os: osx
      osx_image: xcode8.2
      node_js: 4
    - os: osx
      osx_image: xcode8.2
      node_js: 6